### ISSUE TITLE
SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by shenghe** [LLK/scratch-l10n#64]
run "npm run build", it raises exception:

```
import * as fs from 'fs';
       ^
SyntaxError: Unexpected token *
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:696:28)
    at Module._compile (D:\scratch-l10n\node_modules\pirates\lib\index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Object.newLoader [as .js] (D:\scratch-l10n\node_modules\pirates\lib\index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scratch-l10n@3.1.0 build:data: `babel-node scripts/build-data`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scratch-l10n@3.1.0 build:data script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
scratch-l10n: latest
npm:  v6.5.0
node: v11.8.0

**Comment by thisandagain** [comment]
This module isn't meant for direct use (most of the files are generated via Transifex). What are you looking to do here?
